name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.0'  # 必要に応じてGoのバージョンを変更

      - name: Build
        run: go build -o ppv.exe

      - name: Install Inno Setup
        run: choco install innosetup

      - name: Create Installer
        run: '"C:\\Program Files (x86)\\Inno Setup 6\\ISCC.exe" installer.iss'

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: installer
          path: ./pypi-versions-setup.exe

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: installer

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          files: pypi-versions-setup.exe